services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-tourism}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASS: ${POSTGRES_PASSWORD:-postgres}
      DB_NAME: ${POSTGRES_DB:-tourism}
    ports:
      - "8080:8080"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASS: ${POSTGRES_PASSWORD:-postgres}
      DB_NAME: ${POSTGRES_DB:-tourism}
      BOT_TOKEN: ${BOT_TOKEN}
    # Основной бот не требует открытых портов (работает через long polling)

  support_bot:
    build:
      context: .
      dockerfile: Dockerfile.support
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASS: ${POSTGRES_PASSWORD:-postgres}
      DB_NAME: ${POSTGRES_DB:-tourism}
      SUPPORT_BOT_TOKEN: ${SUPPORT_BOT_TOKEN}

volumes:
  db_data:
